services:
    quvels-auth:
        container_name: quvels_auth
        image: quvels_auth:1.0.0
        build:
            context: ../../
            target: development
            dockerfile: ./apps/auth/Dockerfile
        command: npm run start:debug-container auth 
        ports:
            - 3001:3001
            - 3002:3002
            - 9229:9229
        networks:
            - quvels-network
        volumes:
            - ../../:/usr/src/app/
        restart: unless-stopped
networks:
    quvels-network: